// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdr59wK2YuqQGOAoecPr34zDfRDHrZbsk',
    appId: '1:234693759164:web:feae561263eb5c66bf40b9',
    messagingSenderId: '234693759164',
    projectId: 'test-e7b9f-454a0',
    authDomain: 'test-e7b9f-454a0.firebaseapp.com',
    storageBucket: 'test-e7b9f-454a0.firebasestorage.app',
    measurementId: 'G-ZHQ2NX7N26',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYpTS5BkKWEAo_obxbieODoDsGHpBLk9g',
    appId: '1:234693759164:android:f6e669f2012a5b9dbf40b9',
    messagingSenderId: '234693759164',
    projectId: 'test-e7b9f-454a0',
    storageBucket: 'test-e7b9f-454a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhbgk4x7EVQtNNolK2MHv-5cjAb1PN3Ds',
    appId: '1:234693759164:ios:81e22db6bba087e1bf40b9',
    messagingSenderId: '234693759164',
    projectId: 'test-e7b9f-454a0',
    storageBucket: 'test-e7b9f-454a0.firebasestorage.app',
    iosBundleId: 'com.example.firestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhbgk4x7EVQtNNolK2MHv-5cjAb1PN3Ds',
    appId: '1:234693759164:ios:81e22db6bba087e1bf40b9',
    messagingSenderId: '234693759164',
    projectId: 'test-e7b9f-454a0',
    storageBucket: 'test-e7b9f-454a0.firebasestorage.app',
    iosBundleId: 'com.example.firestore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdr59wK2YuqQGOAoecPr34zDfRDHrZbsk',
    appId: '1:234693759164:web:18514c9feeb1455cbf40b9',
    messagingSenderId: '234693759164',
    projectId: 'test-e7b9f-454a0',
    authDomain: 'test-e7b9f-454a0.firebaseapp.com',
    storageBucket: 'test-e7b9f-454a0.firebasestorage.app',
    measurementId: 'G-X96F4QBNV6',
  );
}
